version: '3.8'

services:
  file-server-httpd:
    image: deweiliu/file-server-httpd:latest
    build:
      context: ./httpd/src
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    ports:
      - 80:80
    container_name: file-server-httpd-container