pipeline {
    agent {
        label 'deployer-slave-amazon-linux'
    }
    
    options {
        timeout(time: 90, unit: 'MINUTES')
        timestamps ()
    }

    stages {
        stage('Wait for Stack Ready - httpd'){
            steps{
                sh(script: 'aws cloudformation wait stack-update-complete --region eu-west-2 --stack-name Blog', returnStatus: true)
            }
        }

        stage('CDK Synth - httpd'){
            steps{
                dir('httpd/cdk'){
                    sh '''
                    npm install;
                    npm run synth;
                    '''
                }
            }
        }        
        stage('CDK Deploy - httpd'){
            steps{
                dir('httpd/cdk-corrected'){
                    sh '''
                    npm install;
                    npm run deploy;
                    '''
                }
            }
        }

    }
    post { 
        always { 
            cleanWs()
        }
    }
}
