version: '3.8'

services:
  httpd:
    image: deweiliu/httpd:latest
    build:
      context: ./src
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    ports:
      - 80:80
    container_name: httpd-container